### ISSUE TITLE
Browserify not working upon save 

### ISSUE THREAD

**Issue by hawkerboy7** [Industrial/id-builder#12]
Upon saving a .coffee file (src/js/app.coffee) "watchCoffeescript" is triggerd but that's it.
"watchBrowserify" should in turn be triggered (I think) but it isn't so no new app.bundle.js is being made.
Browserify does work (when starting idbuilder.js), it's only the trigger to start a new Browserify build that doesn't go through for some reason. 

EDIT:
It isn't browserify but upon save i get this:
watchCoffeescript: src/client/js/main.coffee => build/client/js/main.coffee

So watch coffee only copies insead of turning it into .js.
Saving a .js file in the build folder triggers browserify to compile!

**Comment by Industrial** [comment]
Woww that's weird. I should really start writing meaningful unit and integration tests soon, only I would love to change the format of the library to be ES6 class/oo.

I think I'= might already fixed this on the development branch. Coul you check it @hawkerboy?

**Comment by hawkerboy7** [comment]
I'll check now

**Comment by hawkerboy7** [comment]
I think I did everything correctly in getting the development branch to work in my project and it's still doing:
+ 2015-03-03T23:26:22+01:00 watchCoffeescript: src/client/js/app.coffee => build/client/js/app.coffee
Opon save instead of making a .js file.
However the .coffee file has been turned into a .js file (in code) only the extension has remained .coffee

**Comment by hawkerboy7** [comment]
All .coffee files are compiled to .js files on start up.
Afterwards (on save) .coffee files from every location (client and server) are compiled into a .js file but the extension remained .coffee. This is the problem I think

**Comment by hawkerboy7** [comment]
This is fixed in the current development branch!
