### ISSUE TITLE
Require .Jade doesn't return a html function 

### ISSUE THREAD

**Issue by hawkerboy7** [Industrial/id-builder#13]
``` template = require '../templates/main' ```
``` console.log template ```
``` returns {} ```

Instead of the expected function in which you can pass an object with values.

**Comment by hawkerboy7** [comment]
![jade](https://cloud.githubusercontent.com/assets/2284480/6517308/f206576c-c399-11e4-95f8-76af66af4e85.png)

**Comment by hawkerboy7** [comment]
Tried to find the problem, so made a simple app.js
The .jade -> .js file is in the app.bundle.js.
Also if you run the function you will get a good response.
Explicitly returning the function back to require (return test;) doesn't change the output.
So it looks like something goes wrong inside require function. 

![screenshot from 2015-03-12 18 21 49](https://cloud.githubusercontent.com/assets/2284480/6623744/381c387a-c8e5-11e4-8d11-0ececceea5ae.png)

**Comment by hawkerboy7** [comment]
Adding ```module.exports = ``` to the jade part of the app.bundle.js appears to solve this problem.
Now running ```template()``` returns the html string you want.

![screenshot from 2015-03-12 20 32 00](https://cloud.githubusercontent.com/assets/2284480/6626494/3bf129f8-c8f7-11e4-89cb-375c85f78939.png)


However in trying to solve this problem two new problems emerged.
1.) Saving a .jade file in the src doesn't trigger a new build of the jade -> .js file because the debug log shows that jade.sourceFilePathMatches => false (which should be true). This is probably the same as the previous .coffee issue.

2.)  If the .jade template contains things like ``` div=name ``` the follwing line is added into the .jade: ```<div>" + (jade.escape(null == (jade_interp = name) ? "" : jade_interp)) + "</div>")```. The problem here is that __jade__ isn't defined.
Writing ```window.jade = require('jade');``` doesn't help

**Comment by hawkerboy7** [comment]
Using pull request https://github.com/Industrial/id-builder/pull/21 and the following code, you can use jade templates and insert an object with values.

```
{ runtime } = require 'jade'
window.jade = runtime

template	= require '../templates/main'

console.log template()
console.log template
				name: 'My Name'
```


![screenshot from 2015-03-12 23 13 30](https://cloud.githubusercontent.com/assets/2284480/6629348/92bc6cd2-c90d-11e4-8b3e-ac3aa7bc1ed1.png)


It's probably nice if this code is added to app.bundle.js automatically without the user having to require the jade runtime.

**Comment by Industrial** [comment]
Solved in develop
