### ISSUE TITLE
Less @import

### ISSUE THREAD

**Issue by hawkerboy7** [Industrial/id-builder#2]
Any import I try to make doesn't work.
The compiler cannot find the file I am trying to import.

I tried 
- @import "library";
- @import "library.less";
- @import "./library.less";

I have:
src/
  client/
    css/
      app.less
      library.less

_The error_
handlePath { enabled: true,
  watchPath: 'build',
  sourcePath: 'build/test',
  reporter: 'spec',
  taskName: 'watchTests' } src/client/css/app.less
build src/client/css/app.less
buildFilePathMatches false false
{ [Error: 'library.less' wasn't found. Tried - library.less,library.less]
  type: 'File',
  filename: 'input',
  index: 43,
  line: 8,
  callLine: NaN,
  callExtract: undefined,
  column: 0,
  extract: [ '', '@import "library" ;', '' ],
  message: '\'library.less\' wasn\'t found. Tried - library.less,library.less',
  stack: undefined }

I also tried 
- @import "/full/path/to/file/library.less";

This resulted in no error, only 
buildFilePathMatches false false
Both files where compiled but library was not imported into app.less -> app.css

**Comment by hawkerboy7** [comment]
Using @import "src/client/css/library";
Works, however this only works on first build (when the id-builder runs evertything the first time).
On save I get this and nothing changes.

handlePath { enabled: true,
  watchPath: 'build',
  sourcePath: 'build/test',
  reporter: 'spec',
  taskName: 'watchTests' } src/client/css/app.less
build src/client/css/app.less
buildFilePathMatches false false
2015-02-21T13:51:11+01:00 watchLess: src/client/css/app.less => build/client/css/app.less

**Comment by Industrial** [comment]
Ah thanks for the update/comment on this, I am working on it right now.

**Comment by Industrial** [comment]
I also cannot get this working and get the same errors.

**Comment by Industrial** [comment]
By the way if there is any functionality that you would like to see added, new language features etc you can make tickets all you want :D
