### ISSUE TITLE
Run servers error when it is disabled

### ISSUE THREAD

**Issue by hawkerboy7** [Industrial/id-builder#23]
I changed my settings like this:

```javascript
tasks: {
	runServers: {
		enabled: false,
		sourcePath: 'build/server',
		paths: ['app.js']
	}
}
```
Now on save app.coffee I get the following error.
```
/id-builder/build/lib/servers.js:33
  monitor.kill(true);
TypeError: Cannot call method 'kill' of undefined
```
Probably due to the monitor not containing the child_process or something similar that should normally run app.js

**Comment by hawkerboy7** [comment]
This problem occurs because watchServers was still enabled, so on change it tries to restart something that issn't there to begin with. `watchServers: { enabled: false }` Solves it. But if runServers is false watch should be made false too by id-builder. The same maybe holds for other tasks too?
```

```

**Comment by Industrial** [comment]
I might get time for id-builder this weekend again, but I'm thinking this: Maybe the watch tasks should all be condensed into one watch task, that turns on the watch functionality of a compile task when that one is enabled. That would mean that I would have to bundle the functionality of compiling and watching into one thing and then then whole architecture starts to sound more like a plugin architecture. That's what I wanted to avoid with this project. I don't want to rebuild gulp or grunt but DRY instead (yet still configurable).

**Comment by Industrial** [comment]
On a second thought, I think the right way to look at id-builder is to provide a "live" coding environment.

Why have compile targets at all? Make everything watchable and include the initial compile into the watch functionality.

**Comment by hawkerboy7** [comment]
Ahh great I was hoping for a new release with all the cool fixes :) Yes exactly, why would you even want to compile __once__? I too think that would be a good flow! Looking forward to the next version :)

**Comment by Industrial** [comment]
I've created a separate ticket (https://github.com/Industrial/id-builder/issues/27) to handle this issue. Thanks!
