### ISSUE TITLE
Browserify with client .jade

### ISSUE THREAD

**Issue by hawkerboy7** [Industrial/id-builder#24]
When a .jade file is changed in the client folder an event for `browserify` to create a new app.bundle.js should to be triggered. Once that's done `watchBrowsersync` should be triggered. Now only `watchBrowsersync` gets triggerd.

**Comment by Industrial** [comment]
@hawkerboy7: Could you verify that this still happens in the current development branch?

I'm getting

```
id-builder info   watchJade src/client/foo.jade => build/client/foo.jade
id-builder info   watchBrowsersync Reloaded `build/client/foo.jade`
```

**Comment by hawkerboy7** [comment]
watchJade creates a .js file with the .jade extention. If you fix that to be a .js extention I think it will work correctly!

**Comment by hawkerboy7** [comment]
Also when I change the build/client/templates/**.jade browserify gets trigger to early the same way it does  in https://github.com/Industrial/id-builder/issues/25

**Comment by Industrial** [comment]
the build dir shouldn't include .jade files in the client dir, those should all have been converted to js.

I hope this fixes the rename problem :-)

**Comment by hawkerboy7** [comment]
Removing the ^ works!
