### ISSUE TITLE
Browserify get's triggered to early? In 1.7.0 Develop branch

### ISSUE THREAD

**Issue by hawkerboy7** [Industrial/id-builder#25]
Saving a file (for example src/client/js/app.coffee) creates a new (build/client/js/app.js) file correctly.
However browserify appears to be behind "one save" I don't know how to better describe it so I made an example of steps to show what happens.
So:
- app.coffee is empty                                   -> Save -> Browser console shows nothing (this is good)
- app.coffee contains: console.log 'test'       -> Save -> Browser console shows nothing (this is bad)
- app.coffee still contains: console.log 'test' -> Save -> Browser console shows 'test' (this is good)
- app.coffee is empty again                          -> Save -> Browser console shows 'test' (this is bad)
- app.coffee contains: console.log 'test2'     -> Save -> Browser console shows nothing (this is bad)
- app.coffee is empty again                          -> Save -> Browser console shows 'test2' (this is bad)

I think Browserify is somehow triggered before .coffee -> .js is finished.
The app bundle is incorrect.
Changing the app bundle triggers watchBrowsersync which does what is should do so that's not the problem.

**Comment by Industrial** [comment]
Unfortunately I can't reproduce this behaviour with the current development branch:



- foo.coffee is empty -> Save -> Browser logs nothing.
- foo.coffee contains `module.exports = -> 'WHAT'` -> Save -> Browser logs `function () { return 'WHAT'; }`.

**Comment by hawkerboy7** [comment]
With the .jade fix https://github.com/Industrial/id-builder/issues/24 it works correctly now..
I'll recheck with a clean install again if this problem still occurs in development

**Comment by Industrial** [comment]
yay!

**Comment by hawkerboy7** [comment]
Sorry it's still not working correctly.
Removing the ^ has solved the .jade problem but not this problem with browserify...
It's really weird...
I change the build/client/templates/template.js file (which is a jade turned into .js) and the following gets triggered:
```
id-builder info   watchTests Skipping: Directory `build/test` not found.
id-builder info   watchBrowsersync Reloaded `build/client/js/app.bundle.js`
id-builder info   watchBrowserify build/client/js/app.js => build/client/js/app.bundle.js
id-builder info   watchTests Skipping: Directory `build/test` not found.
```
So the reload get triggerd before the app bundle is finished?
I though this could be the problem, but then reloading the page a few seconds later should show the new app.bundle.js.
This is not the case, it remains the 'old' one without the new changes.
Also opening the source http://localhost:8000/js/app.bundle.js shows the 'old' version.

**Comment by hawkerboy7** [comment]
When I start id-builder it looks like this
![step 1](https://cloud.githubusercontent.com/assets/2284480/6989809/c85ddf2e-da60-11e4-9a9a-c70e57526188.png)

Then the first time I save a .coffee file in the src/client/js/**.js only watchCoffee get's triggered.
![step 2](https://cloud.githubusercontent.com/assets/2284480/6989820/e7ef9684-da60-11e4-8f15-b1153fff33a7.png)

Then the second time I press save the following gets triggered
![step3](https://cloud.githubusercontent.com/assets/2284480/6989824/f5c82e9c-da60-11e4-9426-7332092f04d7.png)

I think this causes the problem of browserify being behind one step, even though I don't understand why...
