### ISSUE TITLE
Forever doesn't start the server

### ISSUE THREAD

**Issue by hawkerboy7** [Industrial/id-builder#3]
Upon a clean install I have the following layout and content!

[screenshot from 2015-03-01 15 04 41](https://cloud.githubusercontent.com/assets/2284480/6431081/514d3fac-c024-11e4-8de6-80994ef20c25.png)

When i run app.js it tells me SERVER JS!
Running node build.js results in clean -> compileStylus, compileLivescript, compileLess, compileJade, compileCopy, compileCoffeescript, compileBabel - Start and Finish.
However the server (build/server/app.js) doesn't start!

So my program gets compiled but it doesn't get started

**Comment by Industrial** [comment]
This should be fixed with 1.5.1, can you confirm this @hawkerboy7 ?

**Comment by hawkerboy7** [comment]
It's fixed! Thx!
