### ISSUE TITLE
The logger doesn't log objects. It only .toString()'s them

### ISSUE THREAD

**Issue by Industrial** [Industrial/id-builder#30]
This is very annoying for development. I need to investigate this and find a better alternative.

**Comment by hawkerboy7** [comment]
Check out my logger module https://github.com/hawkerboy7/de-logger.
https://github.com/hawkerboy7/de-logger/blob/master/src/server/logger.coffee#L149
I had the same problem and solved it by creating a new array `result = []`, pushing all required arguments to it and then call `console.log.apply null, result`
