### ISSUE TITLE
Templates are not changed to .js

### ISSUE THREAD

**Issue by hawkerboy7** [Industrial/id-builder#32]
Upon clean install off `id-builder 1.8.1` templates (`.jade` files in the `src/client/templates`) are not being transformed into `template.js` but remain `template.jade`. Also the content of the files still remains a `.jade` file!

**Comment by Industrial** [comment]
Jade is now included as a browserify compiler, that's what fixed the other ticket. So this behaviour is correct and they end up as precompiled js templates including the runtime through jadeify.

**Comment by hawkerboy7** [comment]
Ok so how should I include a .jade template into my js / coffee files?
Now I am getting errors:
```coffeescript
template	= require '../templates/navigation'
```
```
error: Cannot find module '../templates/navigation'
```
The folder `build/client/templates/navigation` only contains a file `index.jade` copied from the src dir.

**Comment by Industrial** [comment]
Yes, correct :) sorry for all the API breaking changes man. I'm not the best project manager :p

Jade should be good now for the future ....

**Comment by Industrial** [comment]
I really want to implement Cucumber.js testing, and then do proper integration tests for the while system. I don't want to keep paching stuff here and breaking it there.
