### ISSUE TITLE
Jadeify need jade installed

### ISSUE THREAD

**Issue by hawkerboy7** [Industrial/id-builder#33]
`id-builder` need _my_ project to have `jade` installed. Without it it won't `jadeify` the `.jade` templates into the `app.bundle.js`. I think you made a pull request over at jadeify to make the require path different?
Maybe it isn't set correctly yet?
It's a clean install of `id-builder 1.8.1`
After starting node build: `Error: Cannot find module 'jade'`
`/node_modules/id-builder/node_modules/jadeify/lib/jadeify.js:4:12`

**Comment by Industrial** [comment]
https://github.com/Industrial/test-id-builder

**Comment by Industrial** [comment]
I've implemented a minimal example that should correctly build an app.bundle.js with jade supported.

**Comment by hawkerboy7** [comment]
Your example works... Strange mine doesn't. I'll check the code again later this week!
