### ISSUE TITLE
Unify creating directory layouts when they don't exist.

### ISSUE THREAD

**Issue by Industrial** [Industrial/id-builder#5]
I don't think having id-builder error out on your projects if you haven't gotten directories set up on disk as the paths in the configuration indicate. I'm not sure what the best approach here is. 

The most DRY approach would be to just take any configured path and create it if it isn't there. Why would you otherwise configure it?

**Comment by hawkerboy7** [comment]
I agree, just check if the basic folders are in the project (src, src/client, src/server, src/tests, build).
If not create them.
These folders you set in the config object of id-builder.
Otherwise it will takes the defaults.

**Comment by hawkerboy7** [comment]
Maybe add the functionality of creating a empty project for you based on your settings (or the default settings)?
So for example:
__node idbuilder.js --new-project__
+ src/
+ src/client/
+ src/client/js
+ src/client/js/app.js (containing "console.log("Default build");"
+ src/client/styles
+ src/client/styles/app.less (containing "html { background-color: #faa; }"
