### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by Industrial** [Industrial/id-builder#6]
Logging could use colours and shaping. I'm not sure having a date stamp with every message is really something that's all that interesting. Using some UTF8 decorations might be nice.

Watcha think about this:
```
 + clean
   clean: build/client
   clean: build/lib
   clean: build/server
 - clean
 + compileStylus
 + compileLivescript
 + compileLess
 + compileJade
 + compileCopy
 + compileCoffeescript
 + compileBabel
   compileLess: src/client/styles/app.less => build/client/styles/app.css
 - compileLess
 - compileStylus
 - compileJade
 - compileLivescript
 - compileCoffeescript
   compileCopy: src/client/css/bootstrap-cyborg.css => build/client/css/bootstrap-cyborg.css
   compileBabel: src/client/js/components/CMS/Users/Pagination.js => build/client/js/components/CMS/Users/Pagination.js
 - compileBabel
 + compileBrowserify
   compileBrowserify: build/client/js/app.js => build/client/js/app.bundle.js
 - compileBrowserify
 + runTests
 + runServers
 + runBrowsersyncServer
 ! runTests: Skipping: Directory `build/test` not found.
 - runTests
 + watchBrowserify
 + watch
 - watch
 + watchTests
 + watchStylus
 + watchServers
 + watchLivescript
 + watchLess
 + watchJade
 + watchCopy
 + watchCoffeescript
 + watchBabel
 - runBrowsersyncServer
 + watchBrowsersync
```

**Comment by hawkerboy7** [comment]
I would leave time stamps  out.
Usually you only need time stamps when you are not watching a running project and want to know when something happens. So probably only on a live version of you project.

+ - ! Are great! 

Colors I don't know yet.
Could be useful but may also make it too colorful if a lot of different things happen.
Maybe highlight the task names only?
Maybe error's in red and adding a \n before and after could make them easier to see?

**Comment by hawkerboy7** [comment]
Or maybe allow time stamp trough the config but leave it out by default. (Also make the time stamp a different color)?

**Comment by Industrial** [comment]
I'm going to have to complete https://github.com/Industrial/id-builder/issues/18 first.

**Comment by Industrial** [comment]
Done with 1.6.0
